---
- name: Install pip
  become: True
  become_method: sudo
  package:
    name: python3-pip
    state: present
    update_cache: "yes"

- name: Update PATH
  ansible.builtin.shell:
    cmd: export PATH=$PATH:/home/vagrant/.local/bin 

- name: Update PATH in .bashrc
  ansible.builtin.lineinfile:
    path: /home/{{ ansible_user_id }}/.bashrc
    line: export PATH=$PATH:/home/vagrant/.local/bin 
    create: yes

- name: pip self-update
  pip:
    name: pip
    state: latest