---
- name: Install packages that allow apt to be used over HTTPS
  become: True
  become_method: sudo
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: "yes"
  vars:
    packages:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - nano
    - net-tools
    - openssl
    - ovmf  
    - software-properties-common