---
- name: Check python version
  shell: python3 --version | cut -f 2 -d ' '
  ignore_errors: True
  register: python_version

- debug:
    msg: "{{ python_version.stdout }}" 

- name: Unarchive Python-3.10.5.tar.xz from www.python.org
  ansible.builtin.unarchive:
    src: https://www.python.org/ftp/python/3.10.5/Python-3.10.5.tar.xz
    dest: '/home/{{ansible_user_id}}/'
    validate_certs: True
    remote_src: yes
  when: python_version.stdout != "3.10.5"

- name: configure
  become: True
  become_method: sudo
  ansible.builtin.shell:
    cmd: ./configure --enable-optimizations
    chdir: /home/{{ansible_user_id}}/Python-3.10.5
  when: python_version.stdout != "3.10.5"

- name: make
  become: True
  become_method: sudo
  community.general.make:
    chdir: /home/{{ansible_user_id}}/Python-3.10.5
  when: python_version.stdout != "3.10.5"

- name: make install
  become: True
  become_method: sudo
  community.general.make:
    chdir: /home/{{ansible_user_id}}/Python-3.10.5
    target: install
  when: python_version.stdout != "3.10.5"

- name: Link python to python3
  ansible.builtin.lineinfile:
    path: /home/{{ ansible_user_id }}/.bashrc
    line: alias python=/usr/local/bin/python3
    create: yes
  when: python_version.stdout != "3.10.5"
